### ISSUE TITLE
Case error in Junos.tmLanguage Load

### ISSUE THREAD

**Issue by fudnet** [codeout/vscode-junos#27]
When loading the plugin for a Juniper JUNOS configuration file, all features including syntax highlighting fail to work. Using developer console, the error is show as an attempt to load:
`~/.vscode/extensions/codeout.vscode-junos-0.3.4/vscode-junos-syntax/syntaxes/Junos.tmLanguage`
when the file is named:
`~/.vscode/extensions/codeout.vscode-junos-0.3.4/vscode-junos-syntax/syntaxes/junos.tmLanguage`
(case issue on the filename)

I am happy to submit a pull request, but unsure if the preference here is to fix the package.json or the actual filename.

Note, this issue only exists on case sensitive filesystems (Linux in my case).

**Comment by fudnet** [comment]
Environmental details:
VSCode Version: v1.89.1
Extension Version: v0.3.4

**Comment by codeout** [comment]
Thank you for your reporting, it would be appreciated if you could open a pull request. I have tested this extension only on case-insensitive systems.

> but unsure if the preference here is to fix the package.json or the actual filename.

We should modify `package.json` because [the upstream](https://github.com/woodjme/vscode-junos-syntax/tree/master/syntaxes) determined the filename even if it's not been actively maintained recently.

**Comment by codeout** [comment]
I've merged your PR and published v0.3.5.
Please try it if you have time, and re-open this issue if you see any further problems.

Thanks again for your report and PR!

**Comment by fudnet** [comment]
Tested and working as expected with v0.3.5. Thank you!
